travis:
  secure:
    BINSTAR_TOKEN: pGG24F34bcoaMuSN5AV8nsEOxGpnR/BHMSdaehjOpR/qqiW/HgX6hShA0XeR+QT/8urnvCqAg9FPpKWiwA8EmQvzMoWya3xeY/f9JlDGsDAEbeOzdfIFVsyBJYmSROg5fDIXawibb2VReGQLJWe5MPwNq8UOIiKZUF2sl5/TWfZ5DTbK0dPxMi4QI50v1EsKzSclMxyYoXRg8CR7Jf8tCqOn5vH5Yk8dXVuQHbVl62IZFDch6kqBrmjDOddhzY+ClLc4x0mN5kHTD2BHWLjDvzE9CTuCJa070rmkI3VLtz4RiVz2mBRNWrQrcfLBfa1Szu0tqqgoqtd9MOhn5cAiPnGJqrUfMh2oyu7p3Y6eaMn0VPNvf4fZ1R0zwm2e/0382WNuRZGYsHUsMeqwXMPbuGFv3kNTZiGuQDT3mDnJ2+YEJnY4q8F9xYSQdTyFV0RPwz52uUA5vQxVKZGFxf60UvfYTkYC6He9EVBI6M2/C8472qY1SHu84tnduT3lf7dZbtMacS7nsH2VmVi2cq295giJ+hpMfQKibLClSkDw4Gx47k5RPUJ4VVKnC55WzQTEX4CTk6ekJ/BNRTrNoc6WDjuwSMoUl5Tfw8sxg4HnmbZdV2gVTyIvrx51rJm6WxmTeZcHAW7VwTve5wl1DL20GDOTr3UoEmsM5NueGGRXS7c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
