travis:
  secure:
    BINSTAR_TOKEN: FBCTSGQbEoUyUBw3XUCImLzkv+ZoIZ7Y5Grw6u10fNv/Q6WMJ9aMjdUFW/YuGQa+jM5eBbFQWKmlSWMJ6U42xugHQKIediXOK/EJUAAiBw0EQBA6r+IxU+Hs9dlwdBDEL1yiziCYNl5tf3ipEYgVCyOizeisf1wjJ5dNrBYGrVbtp5+c0o1uMRrmbBiePpgz2iNS3AtZdVAUYXoN1DT0X9WsVht809OAUN6JL0urvw2oW94reXAtRC7TCsV9C0xlXDTxc7ndYzmgjGZLDFOs1QpzZTs/kuCFqr5OXYss5Z4eX1qvIQ/eY9K0UhgecVoCED5VkGwFiUAD12r8x5X/VdYf5rJuvNwCfp6aI7EuOebwOEIC7Pu58ikrILxFhBLO3Z6l7EMHDQToY5xPm9o/rrFD31UXQlfJgzb0FzYtmXdFwwCLukILDrWV7n2o+lJKnMUclg/3vM+8IbjodEhbY5W2Wi98yObXJc0Xm5NJFDnDWy55x3+ZN9+gyD18/2qSQL69L0ZZlteT41NrS6KXo3Nhg2HRGVVVKhQpWL4ZAXrUjXEJn7OZXHg9HDa9VBgoKXhRmcjOUPkfGdbriC7dSqZ0Ogq84ukjHkwdtdQmTkVcJXIOWeJb4dR1fQHi6FmFVojpT+vNReXosdxXdmWAu2NcOULoVVh2jCqz9B/3LDs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
